# Generated by Django 4.0 on 2021-12-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LAWDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=32, null=True, verbose_name='犯罪嫌疑人')),
                ('uage', models.CharField(max_length=32, null=True, verbose_name='犯罪嫌疑人出生年月')),
                ('uplace', models.CharField(max_length=64, null=True, verbose_name='犯罪嫌疑人出生地')),
                ('unation', models.CharField(max_length=32, null=True, verbose_name='犯罪嫌疑人民族')),
                ('ugender', models.CharField(max_length=32, null=True, verbose_name='犯罪嫌疑人性别')),
                ('uisagain', models.BooleanField(default=False, verbose_name='是否累犯')),
                ('vtime', models.IntegerField(default=0, verbose_name='审判时间')),
                ('vother', models.TextField(max_length=60000, null=True, verbose_name='其他内容')),
                ('vtext', models.TextField(max_length=60000, null=True, verbose_name='裁判文书')),
            ],
        ),
    ]
