# Generated by Django 4.0 on 2022-01-10 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawdocument',
            name='uisagain',
        ),
    ]
