# Generated by Django 4.0 on 2022-01-12 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_remove_lawdocument_vother_remove_lawdocument_vtext_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawdocument',
            name='uage',
        ),
        migrations.RemoveField(
            model_name='lawdocument',
            name='ugender',
        ),
        migrations.RemoveField(
            model_name='lawdocument',
            name='uname',
        ),
        migrations.RemoveField(
            model_name='lawdocument',
            name='unation',
        ),
        migrations.RemoveField(
            model_name='lawdocument',
            name='uplace',
        ),
        migrations.RemoveField(
            model_name='lawdocument',
            name='vjson',
        ),
        migrations.RemoveField(
            model_name='lawdocument',
            name='vtime',
        ),
    ]
