# Generated by Django 4.0 on 2022-01-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_remove_lawdocument_uage_remove_lawdocument_ugender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawdocument',
            name='uage',
            field=models.CharField(max_length=32, null=True, verbose_name='出生年月'),
        ),
        migrations.AddField(
            model_name='lawdocument',
            name='ugender',
            field=models.CharField(max_length=32, null=True, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='lawdocument',
            name='uname',
            field=models.CharField(max_length=32, null=True, verbose_name='犯罪嫌疑人'),
        ),
        migrations.AddField(
            model_name='lawdocument',
            name='unation',
            field=models.CharField(max_length=32, null=True, verbose_name='民族'),
        ),
        migrations.AddField(
            model_name='lawdocument',
            name='uplace',
            field=models.CharField(max_length=64, null=True, verbose_name='出生地'),
        ),
        migrations.AddField(
            model_name='lawdocument',
            name='vjson',
            field=models.JSONField(default={}, verbose_name='json数据'),
        ),
        migrations.AddField(
            model_name='lawdocument',
            name='vtext',
            field=models.TextField(max_length=60000, null=True, verbose_name='裁判文书'),
        ),
        migrations.AddField(
            model_name='lawdocument',
            name='vtime',
            field=models.IntegerField(default=0, verbose_name='审判时间'),
        ),
    ]
